# Generated by NixCP; do not edit.
# marker: nixcp-generated-module-v1; schema: 1; generator: 1
{ lib, pkgs, ... }: {
  assertions = [{ assertion = pkgs.stdenv.hostPlatform.system == "x86_64-linux"; message = "NixCP requires x86_64-linux"; }];
  environment.etc."nixcp/module-marker".text = "nixcp-generated-module-v1\n";
  services.nginx.enable = true;
  systemd.services."nginx".wantedBy = lib.mkForce [];
  services.mysql.enable = true;
  services.mysql.settings.mysqld.bind-address = "127.0.0.1";
  services.redis.servers.nixcp = { enable = true; bind = "127.0.0.1"; port = 6379; protectedMode = true; }
  services.mysql.ensureDatabases = [ "app" ];
  environment.etc."nixcp/php/8.3/bin/php".source = "${(pkgs.php83.withExtensions ({ enabled, all }: enabled ++ [ phpExtensions.intl phpExtensions.redis ]))}/bin/php";
  environment.etc."nixcp/php/8.4/bin/php".source = "${(pkgs.php84.withExtensions ({ enabled, all }: enabled ++ [ phpExtensions.intl phpExtensions.redis ]))}/bin/php";
}
