# Generated by NixCP; do not edit.
# marker: nixcp-generated-module-v1; schema: 1; generator: 1
{ lib, pkgs, ... }: {
  assertions = [{ assertion = pkgs.stdenv.hostPlatform.system == "x86_64-linux"; message = "NixCP requires x86_64-linux"; }];
  environment.etc."nixcp/module-marker".text = "nixcp-generated-module-v1\n";
  services.nginx.enable = true;
  environment.etc."nixcp/composer/bin/composer".source = "${pkgs.phpPackages.composer}/bin/composer";
  environment.etc."nixcp/php/8.3/bin/php".source = "${(pkgs.php83.withExtensions ({ enabled, all }: enabled ++ [ all.intl all.redis ]))}/bin/php";
  environment.etc."nixcp/php/8.4/bin/php".source = "${(pkgs.php84.withExtensions ({ enabled, all }: enabled ++ [ all.intl all.redis ]))}/bin/php";
  services.phpfpm.pools."nixcp-example-test" = { user = "nixcp"; group = "users"; phpPackage = pkgs.php84; settings = { "listen.owner" = "nginx"; "listen.group" = "nginx"; "listen.mode" = "0660"; pm = "dynamic"; "pm.max_children" = 4; "pm.start_servers" = 2; "pm.min_spare_servers" = 2; "pm.max_spare_servers" = 2; "pm.max_requests" = 200; }; };
  services.nginx.virtualHosts."example.test" = {
    listen = [{ addr = "0.0.0.0"; port = 80; }];
    root = "/home";
    extraConfig = "";
    locations."/".extraConfig = "try_files $uri $uri/ /index.php?$query_string;";
    locations."~ \.php$".extraConfig = "include ${pkgs.nginx}/conf/fastcgi.conf; fastcgi_pass unix:/run/phpfpm/nixcp-example-test.sock;";
  };
}
