// Package nix renders a complete NixOS module from validated state.
package nix

import (
	"fmt"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/nixcp/nixcp/internal/php"
	"github.com/nixcp/nixcp/internal/state"
)

const (
	Marker           = "nixcp-generated-module-v1"
	GeneratorVersion = "1"
)

// Renderer only accepts fully validated snapshots. It never reads state files
// while rendering: all dynamic content, including custom nginx snippets, is
// embedded in the returned module.
type Renderer struct{}

func (Renderer) Render(s state.Snapshot) ([]byte, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString("# Generated by NixCP; do not edit.\n")
	b.WriteString("# marker: " + Marker + "; schema: 1; generator: " + GeneratorVersion + "\n")
	b.WriteString("{ lib, pkgs, ... }: {\n")
	b.WriteString("  assertions = [{ assertion = pkgs.stdenv.hostPlatform.system == \"x86_64-linux\"; message = \"NixCP requires x86_64-linux\"; }];\n")
	b.WriteString("  environment.etc.\\\"nixcp/module-marker\\\".text = \"" + Marker + "\\n\";\n")
	renderServices(&b, s.Config)
	renderPHP(&b, s.Config)
	for _, site := range sortedSites(s.Sites) {
		renderSite(&b, site)
	}
	b.WriteString("}\n")
	return []byte(b.String()), nil
}

func renderServices(b *strings.Builder, c state.ConfigSnapshot) {
	renderServicePolicy(b, "nginx", c.Services.Nginx, func() {
		b.WriteString("  services.nginx.enable = true;\n")
	})
	renderServicePolicy(b, "mysql", c.Services.MariaDB, func() {
		b.WriteString("  services.mysql.enable = true;\n")
		b.WriteString("  services.mysql.settings.mysqld.bind-address = \"127.0.0.1\";\n")
	})
	renderServicePolicy(b, "redis-nixcp", c.Services.Redis, func() {
		b.WriteString("  services.redis.servers.nixcp = { enable = true; bind = \"127.0.0.1\"; port = 6379; };\n")
	})
}

// Standard NixOS modules keep package/configuration available when enabled.
// wantedBy is explicitly cleared for stopped services so the desired boot policy
// does not imply deletion of their data or configuration.
func renderServicePolicy(b *strings.Builder, unit string, svc state.ServiceConfig, body func()) {
	if !svc.Installed {
		return
	}
	body()
	if svc.DesiredState == "stopped" {
		fmt.Fprintf(b, "  systemd.services.%s.wantedBy = lib.mkForce [];\n", nixString(unit))
	}
}

func renderPHP(b *strings.Builder, c state.ConfigSnapshot) {
	for _, v := range c.PHP.Installed {
		entry, ok := php.Catalog[v]
		if !ok {
			continue
		}
		exts := make([]string, 0, len(c.PHP.Extensions))
		for _, ext := range c.PHP.Extensions {
			if attr, compatible := php.Compatible(v, ext); compatible {
				exts = append(exts, "phpExtensions."+attr)
			}
		}
		// PHP CLI and FPM consumers share this single nixpkgs composition.
		fmt.Fprintf(b, "  environment.etc.%s.source = \"${(pkgs.%s.withExtensions ({ enabled, all }: enabled ++ [ %s ]))}/bin/php\";\n", nixString("nixcp/php/"+v+"/bin/php"), entry.Nixpkgs, strings.Join(exts, " "))
	}
}

func renderSite(b *strings.Builder, s state.SiteConfig) {
	if !s.Enabled {
		return
	}
	// NixCP owns the complete virtual host boundary. Handler content is data,
	// not Nix source, and therefore cannot escape its Nix string context.
	fmt.Fprintf(b, "  services.nginx.virtualHosts.%s = {\n", nixString(s.Domain))
	b.WriteString("    listen = [{ addr = \"0.0.0.0\"; port = 80; }];\n")
	fmt.Fprintf(b, "    root = %s;\n", nixString(s.DocumentRoot))
	b.WriteString("    extraConfig = \"\";\n")
	if s.Nginx.Handler.Type == "custom" && s.Nginx.Handler.Content != "" {
		fmt.Fprintf(b, "    locations.\\\"/\\\".extraConfig = %s;\n", nixString(s.Nginx.Handler.Content))
	} else {
		fmt.Fprintf(b, "    locations.\\\"/\\\".extraConfig = %s;\n", nixString(templateContent(s.Nginx.Handler.Name)))
	}
	b.WriteString("  };\n")
}

func templateContent(name string) string {
	switch name {
	case "wordpress":
		return "try_files $uri $uri/ /index.php?$args;"
	default: // laravel
		return "try_files $uri $uri/ /index.php?$query_string;"
	}
}

// nixString is a deliberately small Nix encoder. Nix double-quoted strings
// accept these escapes and UTF-8 directly. NUL and invalid UTF-8 are rejected
// by replacing them with a visible escape-free replacement, which preserves a
// syntactically safe generated module even for hostile fixture input.
func nixString(value string) string {
	if !utf8.ValidString(value) {
		value = strings.ToValidUTF8(value, "�")
	}
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(value); {
		r, size := utf8.DecodeRuneInString(value[i:])
		if r == '$' && i+1 < len(value) && value[i+1] == '{' {
			// In Nix double-quoted strings ${ starts interpolation. Escaping
			// the dollar keeps snippets and paths as literal data.
			b.WriteString("\\$")
			i++
			continue
		}
		i += size
		switch r {
		case '\\':
			b.WriteString("\\\\")
		case '"':
			b.WriteString("\\\"")
		case '\n':
			b.WriteString("\\n")
		case '\r':
			b.WriteString("\\r")
		case '\t':
			b.WriteString("\\t")
		case 0:
			b.WriteString("�")
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func sortedSites(s []state.SiteConfig) []state.SiteConfig {
	out := append([]state.SiteConfig(nil), s...)
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}
