// Package nix renders a complete NixOS module from validated state.
package nix

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/nixcp/nixcp/internal/state"
)

const Marker = "nixcp-generated-module-v1"

type Renderer struct{}

func (Renderer) Render(s state.Snapshot) ([]byte, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString("# Generated by NixCP; do not edit.\n# " + Marker + "\n{ lib, pkgs, ... }: {\n")
	b.WriteString("  assertions = [{ assertion = pkgs.stdenv.hostPlatform.system == \"x86_64-linux\"; message = \"NixCP requires x86_64-linux\"; }];\n")
	renderServices(&b, s.Config)
	renderPHP(&b, s.Config)
	for _, site := range sortedSites(s.Sites) {
		renderSite(&b, site)
	}
	b.WriteString("}\n")
	return []byte(b.String()), nil
}
func renderServices(b *strings.Builder, c state.ConfigSnapshot) {
	if c.Services.Nginx.Installed {
		b.WriteString("  services.nginx.enable = true;\n")
		if c.Services.Nginx.DesiredState == "stopped" {
			b.WriteString("  systemd.services.nginx.wantedBy = lib.mkForce [];\n")
		}
	}
	if c.Services.MariaDB.Installed {
		b.WriteString("  services.mysql.enable = true;\n  services.mysql.settings.mysqld.bind-address = \"127.0.0.1\";\n")
	}
	if c.Services.Redis.Installed {
		b.WriteString("  services.redis.servers.nixcp = { enable = true; bind = \"127.0.0.1\"; port = 6379; };\n")
	}
}
func renderPHP(b *strings.Builder, c state.ConfigSnapshot) {
	for _, v := range c.PHP.Installed {
		attr := map[string]string{"8.3": "php83", "8.4": "php84"}[v]
		if attr == "" {
			continue
		}
		b.WriteString("  environment.etc.\"nixcp/php/" + v + "/bin/php\".source = \"${pkgs." + attr + "}/bin/php\";\n")
	}
}
func renderSite(b *strings.Builder, s state.SiteConfig) {
	if !s.Enabled {
		return
	}
	name := strconv.Quote(s.Domain)
	root := strconv.Quote(s.DocumentRoot)
	b.WriteString(fmt.Sprintf("  services.nginx.virtualHosts.%s = { listen = [{ addr = \"0.0.0.0\"; port = 80; }]; root = %s; };\n", name, root))
}
func sortedSites(s []state.SiteConfig) []state.SiteConfig {
	out := append([]state.SiteConfig(nil), s...)
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}
