// Package nix renders a complete NixOS module from validated state.
package nix

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/nixcp/nixcp/internal/php"
	"github.com/nixcp/nixcp/internal/state"
)

const (
	Marker           = "nixcp-generated-module-v1"
	GeneratorVersion = "1"
)

// Renderer only accepts fully validated snapshots. It never reads state files
// while rendering: all dynamic content, including custom nginx snippets, is
// embedded in the returned module.
type Renderer struct{}

func (Renderer) Render(s state.Snapshot) ([]byte, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString("# Generated by NixCP; do not edit.\n")
	b.WriteString("# marker: " + Marker + "; schema: 1; generator: " + GeneratorVersion + "\n")
	b.WriteString("{ lib, pkgs, ... }: {\n")
	b.WriteString("  assertions = [{ assertion = pkgs.stdenv.hostPlatform.system == \"x86_64-linux\"; message = \"NixCP requires x86_64-linux\"; }];\n")
	b.WriteString("  environment.etc.\"nixcp/module-marker\".text = \"" + Marker + "\\n\";\n")
	renderServices(&b, s.Config)
	renderMariaDBAccounts(&b, s.Config, s.Sites)
	renderPHP(&b, s.Config)
	for _, site := range sortedSites(s.Sites) {
		renderSite(&b, site, s.Config.Owner.Username)
	}
	b.WriteString("}\n")
	return []byte(b.String()), nil
}

func renderServices(b *strings.Builder, c state.ConfigSnapshot) {
	renderServicePolicy(b, "nginx", c.Services.Nginx, func() {
		b.WriteString("  services.nginx.enable = true;\n")
	})
	renderServicePolicy(b, "mysql", c.Services.MariaDB, func() {
		b.WriteString("  services.mysql.enable = true;\n")
		// NixOS 26.05 requires an explicit services.mysql.package. Pin the
		// supported local database implementation instead of relying on a
		// release-dependent module default.
		b.WriteString("  services.mysql.package = pkgs.mariadb;\n")
		b.WriteString("  services.mysql.settings.mysqld.bind-address = \"127.0.0.1\";\n")
	})
	renderServicePolicy(b, "valkey-nixcp", c.Services.Valkey, func() {
		b.WriteString("  services.redis.package = pkgs.valkey;\n")
		b.WriteString("  services.redis.servers.nixcp = { enable = true; bind = \"127.0.0.1\"; port = 6379; };\n")
	})
	if len(c.MariaDBRegistry.Databases) > 0 {
		values := make([]string, 0, len(c.MariaDBRegistry.Databases))
		for _, database := range c.MariaDBRegistry.Databases {
			values = append(values, nixString(database))
		}
		fmt.Fprintf(b, "  services.mysql.ensureDatabases = [ %s ];\n", strings.Join(values, " "))
	}
}

// Standard NixOS modules keep package/configuration available when enabled.
// wantedBy is explicitly cleared for stopped services so the desired boot policy
// does not imply deletion of their data or configuration.
func renderServicePolicy(b *strings.Builder, unit string, svc state.ServiceConfig, body func()) {
	if !svc.Installed {
		return
	}
	body()
	if svc.DesiredState == "stopped" {
		fmt.Fprintf(b, "  systemd.services.%s.wantedBy = lib.mkForce [];\n", nixString(unit))
	}
}

// nixcpMariaDBSecretPath is the absolute path of the private, 0600 SQL file
// that carries the per-site MariaDB account grants. It lives under the owner's
// state directory (never in the world-readable Nix store) so the generated
// module does not contain any password.
func nixcpMariaDBSecretPath(home string) string {
	return filepath.Join(home, ".nixcp", "secrets", "mariadb", "accounts.sql")
}

// MariaDBAccountsSQL returns the deterministic, idempotent SQL that provisions
// a dedicated account (user = database name) per site database. It is empty
// when no site declares a database. The SQL is written to a private file (see
// nixcpMariaDBSecretPath) and executed by the generated oneshot unit via stdin;
// it is never embedded in the module.
func MariaDBAccountsSQL(c state.ConfigSnapshot, sites []state.SiteConfig) string {
	seen := map[string]bool{}
	var sql strings.Builder
	for _, site := range sortedSites(sites) {
		if site.MariaDB == nil || seen[site.MariaDB.Database] {
			continue
		}
		seen[site.MariaDB.Database] = true
		fmt.Fprintf(&sql, "CREATE USER IF NOT EXISTS '%s'@'localhost' IDENTIFIED BY '%s';\nALTER USER '%s'@'localhost' IDENTIFIED BY '%s';\nGRANT ALL ON `%s`.* TO '%s'@'localhost';\nFLUSH PRIVILEGES;\n", site.MariaDB.User, site.MariaDB.Password, site.MariaDB.User, site.MariaDB.Password, site.MariaDB.Database, site.MariaDB.User)
	}
	return sql.String()
}

// renderMariaDBAccounts emits a deterministic oneshot unit that provisions a
// dedicated account (user = database name) per site database, idempotently. It
// runs after mysql.service and only when MariaDB is installed and desired
// running. The password stays in a private 0600 SQL file under ~/.nixcp and is
// never written into the world-readable Nix store here: the unit only references
// the path to that file and feeds it to mariadb via stdin. The comment carries a
// SHA-256 of the SQL so a password rotation changes the unit text and re-triggers
// the idempotent ALTER USER on the next switch (RemainAfterExit restart).
func renderMariaDBAccounts(b *strings.Builder, c state.ConfigSnapshot, sites []state.SiteConfig) {
	if !c.Services.MariaDB.Installed || c.Services.MariaDB.DesiredState != "running" {
		return
	}
	sql := MariaDBAccountsSQL(c, sites)
	if sql == "" {
		return
	}
	sum := sha256.Sum256([]byte(sql))
	hash := hex.EncodeToString(sum[:])[:16]
	// The client path is a Nix interpolation that must survive the string
	// encoder, so it is carried as a plain-text placeholder and substituted
	// after escaping (nixString would already have escaped any ${…}).
	payload := "# nixcp-mariadb-accounts sha256=" + hash + "\n" +
		"@MARIADB@/bin/mariadb --protocol=socket -u root --batch < " + nixcpMariaDBSecretPath(c.Owner.Home)
	encoded := strings.ReplaceAll(nixString(payload), "@MARIADB@", "${pkgs.mariadb}")
	b.WriteString("  systemd.services.nixcp-mariadb-accounts = {\n")
	b.WriteString("    description = \"NixCP per-site MariaDB accounts\";\n")
	b.WriteString("    after = [ \"mysql.service\" ];\n")
	b.WriteString("    wantedBy = [ \"multi-user.target\" ];\n")
	b.WriteString("    serviceConfig = { Type = \"oneshot\"; RemainAfterExit = true; };\n")
	fmt.Fprintf(b, "    script = %s;\n", encoded)
	b.WriteString("  };\n")
}

func renderPHP(b *strings.Builder, c state.ConfigSnapshot) {
	if len(c.PHP.Installed) > 0 {
		// Keep Composer system-owned and at a stable absolute path. The CLI
		// runs this PHP script through the project-resolved PHP binary.
		b.WriteString("  environment.etc.\"nixcp/composer/bin/composer\".source = \"${pkgs.phpPackages.composer}/bin/composer\";\n")
	}
	for _, v := range c.PHP.Installed {
		entry, ok := php.Catalog[v]
		if !ok {
			continue
		}
		exts := make([]string, 0, len(c.PHP.Extensions))
		for _, ext := range c.PHP.Extensions {
			if attr, compatible := php.Compatible(v, ext); compatible {
				exts = append(exts, "all."+attr)
			}
		}
		// PHP CLI and FPM consumers share this single nixpkgs composition.
		fmt.Fprintf(b, "  environment.etc.%s.source = \"${(pkgs.%s.withExtensions ({ enabled, all }: enabled ++ [ %s ]))}/bin/php\";\n", nixString("nixcp/php/"+v+"/bin/php"), entry.Nixpkgs, strings.Join(exts, " "))
	}
}

func renderSite(b *strings.Builder, s state.SiteConfig, owner string) {
	if !s.Enabled {
		return
	}
	entry := php.Catalog[s.PHP]
	pool := "nixcp-" + s.ID
	socket := "/run/nixcp/php-fpm/" + s.ID + ".sock"
	// Each site gets an isolated pool and a private Unix socket; Nginx is the
	// only peer allowed to reach it. The vhost boundary remains HTTP-only.
	fmt.Fprintf(b, "  services.phpfpm.pools.%s = { user = %s; group = %s; phpPackage = pkgs.%s; settings = { listen = %s; \"listen.owner\" = \"nginx\"; \"listen.group\" = \"nginx\"; \"listen.mode\" = \"0660\"; }; };\n", nixString(pool), nixString(owner), nixString(owner), entry.Nixpkgs, nixString(socket))
	fmt.Fprintf(b, "  services.nginx.virtualHosts.%s = {\n", nixString(s.Domain))
	b.WriteString("    listen = [{ addr = \"0.0.0.0\"; port = 80; }];\n")
	fmt.Fprintf(b, "    root = %s;\n", nixString(s.DocumentRoot))
	b.WriteString("    extraConfig = \"\";\n")
	content := templateContent(s.Nginx.Handler.Name)
	if s.Nginx.Handler.Type == "custom" {
		content = s.Nginx.Handler.Content
	}
	if s.Nginx.Handler.Type == "generic" {
		content = "try_files $uri $uri/ =404;"
	}
	fmt.Fprintf(b, "    locations.\"/\".extraConfig = %s;\n", nixString(content))
	// Keep the Nix package interpolation intentional: nixString escapes `${…}`
	// in dynamic text, but Nginx must receive the resolved store path rather
	// than the literal characters `${pkgs.nginx}`.
	fastCGI := "include @NGINX@/conf/fastcgi.conf; fastcgi_pass unix:" + socket + ";"
	fastCGIEncoded := strings.ReplaceAll(nixString(fastCGI), "@NGINX@", "${pkgs.nginx}")
	fmt.Fprintf(b, "    locations.\"~ \\.php$\".extraConfig = %s;\n", fastCGIEncoded)
	b.WriteString("  };\n")
}

func templateContent(name string) string {
	switch name {
	case "wordpress":
		return "try_files $uri $uri/ /index.php?$args;"
	default: // laravel
		return "try_files $uri $uri/ /index.php?$query_string;"
	}
}

// nixString is a deliberately small Nix encoder. Nix double-quoted strings
// accept these escapes and UTF-8 directly. NUL and invalid UTF-8 are rejected
// by replacing them with a visible escape-free replacement, which preserves a
// syntactically safe generated module even for hostile fixture input.
func nixString(value string) string {
	if !utf8.ValidString(value) {
		value = strings.ToValidUTF8(value, "�")
	}
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(value); {
		r, size := utf8.DecodeRuneInString(value[i:])
		if r == '$' && i+1 < len(value) && value[i+1] == '{' {
			// In Nix double-quoted strings ${ starts interpolation. Escaping
			// the dollar keeps snippets and paths as literal data.
			b.WriteString("\\$")
			i++
			continue
		}
		i += size
		switch r {
		case '\\':
			b.WriteString("\\\\")
		case '"':
			b.WriteString("\\\"")
		case '\n':
			b.WriteString("\\n")
		case '\r':
			b.WriteString("\\r")
		case '\t':
			b.WriteString("\\t")
		case 0:
			b.WriteString("�")
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func sortedSites(s []state.SiteConfig) []state.SiteConfig {
	out := append([]state.SiteConfig(nil), s...)
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}
